// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7g9PgzrqC78HEF7sS61Omz2cN08ijhB0',
    appId: '1:930045843177:web:1c2079007478c06f798278',
    messagingSenderId: '930045843177',
    projectId: 'fcm-notifications-a84d6',
    authDomain: 'fcm-notifications-a84d6.firebaseapp.com',
    storageBucket: 'fcm-notifications-a84d6.appspot.com',
    measurementId: 'G-EQP8QFFJ72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkyp-qBux0cxjJ8LD8RKK4N8X3H08tGHo',
    appId: '1:930045843177:android:2a6667c744ad51a9798278',
    messagingSenderId: '930045843177',
    projectId: 'fcm-notifications-a84d6',
    storageBucket: 'fcm-notifications-a84d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1Fblbf14rWeFgYgf9B993qO9qW7EQOw',
    appId: '1:930045843177:ios:48f8d0162add0c5f798278',
    messagingSenderId: '930045843177',
    projectId: 'fcm-notifications-a84d6',
    storageBucket: 'fcm-notifications-a84d6.appspot.com',
    iosBundleId: 'com.example.fcmNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1Fblbf14rWeFgYgf9B993qO9qW7EQOw',
    appId: '1:930045843177:ios:48f8d0162add0c5f798278',
    messagingSenderId: '930045843177',
    projectId: 'fcm-notifications-a84d6',
    storageBucket: 'fcm-notifications-a84d6.appspot.com',
    iosBundleId: 'com.example.fcmNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7g9PgzrqC78HEF7sS61Omz2cN08ijhB0',
    appId: '1:930045843177:web:0a5d44977184d1aa798278',
    messagingSenderId: '930045843177',
    projectId: 'fcm-notifications-a84d6',
    authDomain: 'fcm-notifications-a84d6.firebaseapp.com',
    storageBucket: 'fcm-notifications-a84d6.appspot.com',
    measurementId: 'G-LPFBRMKTL7',
  );
}
